import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'

const minimalCss = `
html { scroll-behavior: smooth; }
.font-ibarra { font-family: 'Ibarra Real Nova', serif; }
.disc-section h2 { font-family: 'Ibarra Real Nova', serif; font-size: 26px; font-weight: 400; color: #2a2017; margin-bottom: 14px; margin-top: 0; }
.disc-section h3 { font-family: 'Glacial Indifference', sans-serif; font-size: 13px; letter-spacing: 0.18em; text-transform: uppercase; color: #a8865c; margin-bottom: 10px; margin-top: 32px; }
.disc-section p, .disc-section li { font-family: 'Glacial Indifference', sans-serif; font-size: 15.5px; line-height: 1.95; color: #555; }
.disc-section ul { padding-left: 20px; margin: 10px 0; }
.disc-section li { margin-bottom: 6px; }
.disc-divider { width: 40px; height: 1px; background: rgba(168,134,92,0.45); margin: 0 0 28px; }
`

function FU({ children, delay = 0 }) {
  const r = useRef(null)
  const [visible, setVisible] = useState(false)
  useEffect(() => {
    if (!r.current) return
    const io = new IntersectionObserver(([e]) => {
      if (e.isIntersecting) { setVisible(true); io.disconnect() }
    }, { threshold: 0.08 })
    io.observe(r.current)
    return () => io.disconnect()
  }, [])
  return (
    <div
      ref={r}
      className={`transition-[opacity,transform] duration-700 ease-out ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}
      style={{ transitionDelay: `${delay}ms` }}
    >
      {children}
    </div>
  )
}

const SECTIONS = [
  {
    title: 'Nature of Astrological Services',
    items: [
      {
        heading: 'For Guidance Only',
        body: 'Vedic Saar provides astrological readings, numerological analyses, and Vastu consultations for entertainment, self-reflection, and spiritual guidance purposes only. All content offered through our website, chatbot, or personal consultations is intended to provide insight and perspective — not factual predictions about future events.',
      },
      {
        heading: 'Not a Substitute for Professional Advice',
        body: 'Nothing on this website or provided by our astrologers should be construed as medical, psychological, legal, financial, or other professional advice. Always consult a qualified professional for matters concerning your health, legal rights, financial decisions, or mental wellbeing. Vedic Saar expressly disclaims any responsibility for decisions made based on astrological readings.',
      },
    ],
  },
  {
    title: 'No Guarantees of Accuracy',
    items: [
      {
        heading: 'Astrology is Interpretive',
        body: 'Vedic astrology is a complex interpretive tradition with multiple schools of thought. Readings involve the professional judgement of our practitioners and may differ from those of other astrologers. Vedic Saar makes no warranty or guarantee — express or implied — regarding the accuracy, completeness, or fitness for purpose of any reading or recommendation.',
      },
      {
        heading: 'Results May Vary',
        body: 'Individual experiences with astrological guidance vary widely. Past insights provided to other clients are not indicative of the results any specific individual may experience. Astrological conditions described in a reading represent tendencies and energies, not certainties.',
      },
    ],
  },
  {
    title: 'AI Chatbot Disclaimer',
    items: [
      {
        heading: 'AI-Generated Interpretations',
        body: 'Our AI-powered chatbot uses Google Gemini to generate birth chart interpretations based on your supplied birth data. These responses are generated by a language model and are not reviewed by a human astrologer before delivery. They represent pattern-based suggestions and must not be treated as definitive astrological counsel.',
      },
      {
        heading: 'Limitations of AI',
        body: 'AI language models can produce inaccurate, incomplete, or contextually inappropriate responses. Vedic Saar is not liable for any harm or loss resulting from reliance on AI-generated content. For personalised, expert guidance we strongly recommend booking a session with one of our qualified astrologers.',
      },
      {
        heading: 'Free Reading Limits',
        body: 'Free AI readings are provided as a demonstration of our technology. They are subject to daily limits and may be discontinued or altered at any time without notice.',
      },
    ],
  },
  {
    title: 'Gemstones, Rudraksha & Remedies',
    items: [
      {
        heading: 'Information Purposes Only',
        body: 'Information about gemstones, Rudraksha beads, mantras, and Vastu remedies provided on this website is based on traditional Vedic belief systems. Vedic Saar does not claim that these items or practices cure, treat, or prevent any disease or medical condition. Any such claims are expressly disclaimed.',
      },
      {
        heading: 'Individual Suitability',
        body: 'The suitability of a gemstone or remedy depends on many personal factors. Recommendations made during a consultation are the practitioner\'s professional opinion at that point in time. Always consult a qualified healthcare professional before making changes to your physical or mental health regime.',
      },
    ],
  },
  {
    title: 'Limitation of Liability',
    items: [
      {
        heading: 'Extent of Liability',
        body: 'To the fullest extent permitted by applicable law, Vedic Saar, its directors, practitioners, and employees shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of our services or reliance on any information provided. Our total liability, if any, shall not exceed the amount paid for the specific service that gave rise to the claim.',
      },
      {
        heading: 'Force Majeure',
        body: 'Vedic Saar shall not be held responsible for any delay or failure to provide services caused by circumstances beyond our reasonable control, including but not limited to internet outages, API service disruptions, or other technical failures.',
      },
    ],
  },
  {
    title: 'Governing Law',
    items: [
      {
        heading: 'Jurisdiction',
        body: 'This disclaimer and all services provided by Vedic Saar are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in New Delhi, India.',
      },
      {
        heading: 'Acceptance',
        body: 'By using this website or any of our services — including the AI chatbot, booking system, or requesting a consultation — you acknowledge that you have read, understood, and agree to this disclaimer in its entirety.',
      },
    ],
  },
]

export default function Disclaimer() {
  return (
    <>
      <style>{minimalCss}</style>

      {/* Hero */}
      <section className="relative min-h-[320px] bg-[#f7f2ea] flex items-end justify-center overflow-hidden">
        <img src="/assets/costelation.png" alt="" aria-hidden="true"
          className="absolute top-0 left-0 w-[280px] pointer-events-none select-none"
          style={{ opacity: 0.4, zIndex: 1 }} />
        <img src="/assets/crescentmoon.png" alt="" aria-hidden="true"
          className="absolute top-0 right-0 w-[220px] pointer-events-none select-none"
          style={{ opacity: 0.4, zIndex: 1 }} />
        <div className="relative z-[3] text-center pb-10 w-full">
          <p className="text-[10px] tracking-[3px] uppercase text-[#a8865c] mb-4 font-normal"
            style={{ fontFamily: "'Glacial Indifference', sans-serif" }}>
            Vedic Saar · Legal
          </p>
          <h1 className="font-ibarra text-[64px] max-[960px]:text-[40px] font-normal text-black tracking-[2px] leading-none">
            <em>Disclaimer</em>
          </h1>
          <p style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 13, color: '#9a8060', marginTop: 14, letterSpacing: '0.04em' }}>
            Last updated: May 2025
          </p>
        </div>
        <div className="absolute bottom-[-1px] left-0 w-full z-[1] overflow-visible">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 60" preserveAspectRatio="none"
            style={{ display: 'block', width: '100%', height: '60px' }}>
            <path fill="white" d="M0,60 L0,40 Q500,-14 1000,40 L1000,60 Z" />
          </svg>
        </div>
      </section>

      {/* Intro */}
      <section className="bg-white pt-16 pb-10">
        <div className="max-w-[820px] mx-auto px-8 md:px-12">
          <FU>
            {/* Notice banner */}
            <div style={{ background: 'rgba(168,134,92,0.07)', border: '1px solid rgba(168,134,92,0.3)', borderRadius: 8, padding: '16px 24px', marginBottom: 32, display: 'flex', gap: 14, alignItems: 'flex-start' }}>
              <span style={{ color: '#a8865c', fontSize: 20, flexShrink: 0, marginTop: 2 }}>✦</span>
              <p style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 14.5, lineHeight: 1.85, color: '#7a6040', margin: 0 }}>
                <strong>Important:</strong> Vedic Saar's services are intended for spiritual guidance and self-reflection only.
                They do not constitute medical, legal, financial, or psychological advice.
              </p>
            </div>
            <p style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 16.5, lineHeight: 2, color: '#666' }}>
              Please read this disclaimer carefully before using our website, AI chatbot, booking services, or consulting
              with any of our practitioners. By accessing or using Vedic Saar in any capacity, you agree to the terms set
              out below. If you do not agree, please discontinue use of our services.
            </p>
          </FU>
        </div>
      </section>

      {/* Main content */}
      <section className="bg-white pb-24">
        <div className="max-w-[820px] mx-auto px-8 md:px-12">
          {SECTIONS.map((sec, si) => (
            <FU key={sec.title} delay={si * 60}>
              <div className="disc-section mb-14">
                <div className="disc-divider" />
                <h2>{sec.title}</h2>
                {sec.items.map((item) => (
                  <div key={item.heading}>
                    <h3>{item.heading}</h3>
                    <p>{item.body}</p>
                  </div>
                ))}
              </div>
            </FU>
          ))}

          {/* CTA */}
          <FU delay={360}>
            <div style={{ background: '#f7f2ea', border: '1px solid rgba(168,134,92,0.25)', borderRadius: 10, padding: '36px 40px', marginTop: 8 }}>
              <p style={{ fontFamily: "'Jost', sans-serif", fontSize: 10, letterSpacing: '0.22em', textTransform: 'uppercase', color: '#a8865c', marginBottom: 10 }}>
                Questions or Concerns?
              </p>
              <h2 style={{ fontFamily: "'Ibarra Real Nova', serif", fontSize: 24, fontWeight: 400, color: '#2a2017', marginBottom: 12 }}>
                We're Here to Help
              </h2>
              <p style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 15.5, lineHeight: 1.9, color: '#666', marginBottom: 20 }}>
                If you have any questions about this disclaimer or our services, please reach out before booking.
              </p>
              <a
                href="mailto:info@vedicsaar.com"
                style={{
                  display: 'inline-block',
                  fontFamily: "'Glacial Indifference', sans-serif",
                  fontSize: 11,
                  letterSpacing: '0.18em',
                  textTransform: 'uppercase',
                  padding: '12px 28px',
                  background: '#0d0a06',
                  color: '#fff',
                  border: '2px dashed rgba(255,255,255,0.35)',
                  textDecoration: 'none',
                  borderRadius: 0,
                }}
              >
                info@vedicsaar.com
              </a>
            </div>
          </FU>

          {/* Back links */}
          <FU delay={400}>
            <div style={{ marginTop: 40, display: 'flex', gap: 24, flexWrap: 'wrap' }}>
              {[
                { label: 'Privacy Policy', to: '/privacy-policy' },
                { label: 'Terms of Service', to: '/terms-of-service' },
              ].map(({ label, to }) => (
                <Link key={to} to={to}
                  style={{ fontFamily: "'Glacial Indifference', sans-serif", fontSize: 13, color: '#a8865c', textDecoration: 'underline', textUnderlineOffset: 3 }}>
                  {label}
                </Link>
              ))}
            </div>
          </FU>
        </div>
      </section>
    </>
  )
}
